const PACKAGE_ALIAS_DELIMITER = '@';
const PACKAGE_ID_PREFIX = '0Ho';
const PACKAGE_VERSION_ID_PREFIX = '04t';
const SFDX_PROJECT_JSON_FILENAME = './sfdx-project.json';

module.exports = {
    PACKAGE_ALIAS_DELIMITER,
    PACKAGE_ID_PREFIX,
    PACKAGE_VERSION_ID_PREFIX,
    SFDX_PROJECT_JSON_FILENAME
};